#!/bin/sh
PATH=/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
# При обновлении пакета postinst заново соберёт конфиг — ничего не убираем
[ "$1" = upgrade ] && exit 0
/opt/sbin/nfqws-ui-setup remove
exit 0
